[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts"
]

[profile.ci]
fuzz = { runs = 1000 }
verbosity = 3
gas_reports = ["*"]

[profile.gas]
gas_reports = ["*"]

[profile.deploy]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts"
]
optimizer = true
optimizer_runs = 1000000

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
