name: Build and Release  # name it whatever you like
on:
  push:
    tags:
      - 'v*'  # triggered whenever a new tag (prefixed with "v") is pushed to the repository
  pull_request:

jobs:
  release-xusd-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}          # use git tag as unique release name
      release_description: 'XUSD Release'       # some boring placeholder text to attach
      relative_path: '["src/token"]'  # relative path to your really awesome contract
      package: 'excellar-token-contract'                # package name to build
      make_target: 'build-dependencies'             # make target to invoke
    secrets:  # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}    # don't modify this line
