name: Build and Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release-xusd-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'XUSD Release'
      package: 'token'
      make_target: 'build-token'
    secrets:
      release_token: ${{ secrets.GH_API_TOKEN }}
