name: Build and Release  # name it whatever you like
on:
  push:
    tags:
      - 'v*'  # triggered whenever a new tag (prefixed with "v") is pushed to the repository
  pull_request:

jobs:
  release-xusd-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'XUSD Release'
      package: 'token'
      make_target: 'build'
    secrets:
      release_token: ${{ secrets.GH_API_TOKEN }}
